sudo: required
language: python
services: docker
notifications:
  email: false

install: pip3 install -r requirements.txt
before_script: moban

jobs:
  include:
    - stage: generate-pdf
      if: branch = master AND type = push

script:
- docker run --mount src=$TRAVIS_BUILD_DIR/resume,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic --keep-intermediates --reruns 0 main.tex; biber main; tectonic main.tex"

after_success:
  - git config user.email "travis@travis-ci.org"
  - git config user.name "traviscibot"
  - mv resume/**.pdf resume/pdf/
  - git add resume/pdf/**.pdf
  - git commit -m "Run tex to generate pdf [skip ci]"
  - git push https://ayan-b:${GITHUB_TOKEN}@github.com/ayan-b/resume-generator HEAD:master
